const menu_items = [
  {
    id: 1,
    link: "",
    displayName: "Portfolio",
    customClasses: [],
    items: [
      {
        id: "menu-item--codes",
        link: "",
        displayName: "Codes",
        customClasses: ["hover-backend"],
        items: [
          {
            id: "github-repo",
            link: "https://github.com/nightingalemedia",
            displayName: "My Github Repo",
            customClasses: [],
            items: [],
          },
          {
            id: "full-stack-cms",
            link: "https://mjvirtualevents.com/mjp-demo-event",
            displayName: "Full Stack Event CMS",
            customClasses: [],
            items: [],
            info: "My most recent role as a full-stack developer saw me faced with a time-sensitive project to build, manage and customize an application for a consistent influx of clients seeking virtual event experiences.  ** The product is a full-stack application using Strapi as a CMS and Next.js/React as a front-end interactive modular website.  If you want to request a full-demo please contact me.",
          },
          {
            id: "interactive-installations",
            link: "http://emiliebaltz.com/commissions/dream-machine/",
            displayName: "Interactive Installations",
            customClasses: [],
            items: [],
            info: "One of my favorite skills that coding gives me is my ability to help experience-designers to create digitally-savvy installations and experiences.  I use RaspberryPi and Arduinos to help create flashy, interactive and involved experiences. ** I am working to get a gallery of these together, please check back soon!",
          },
          {
            id: "real-time-apps",
            link: "https://mjvirtualevents.com/osu-ccts-annual-scientific-meeting/exhibitors/612",
            displayName: "Real Time Apps",
            customClasses: [],
            items: [],
            info: "Most of my current role as a full-stack developer is to create and integrate real-time logic for virtual event experiences.  ** This includes chat windows, live-auction trackers, web-scrapers, attendee notifications, real-time conversations (presentations) and Q&A areas.  ** Most of this work is behind NDAs however please contact me and I can show you a demo. The link takes you to one example",
          },
          {
            id: "explore-this-site",
            link: "https://github.com/NightingaleMedia/react-portfolio.git",
            displayName: "Explore This Site's Repo",
            customClasses: [],
            items: [],
            info: "Learning React and the many possibilities it offers has been my favorite past-time over the last year. ** I built this site to allow users to scratch the surface of what I have learned.  I hope you enjoy it as much as I do.",
          },
        ],
      },
      {
        id: 2,
        link: "",
        displayName: "Pixels",
        customClasses: ["hover-frontend"],
        items: [
          {
            id: "ecommerce-react",
            link: "https://www.glassroomart.com",
            displayName: "React eCommerce Site",
            customClasses: [],
            items: [],
            info: "Using Gatsby.js, Shopify API and several plugins, I helped a retailer create a more interactive, faster and real-time experience while shopping and booking online classes.**  There was lots of complex logic involved in this, including the extensive Shopify GraphQL API.  Check it out!",
          },
          {
            id: "srcum-boards",
            link: "#skills",
            displayName: "Interactive Scrum Boards",
            customClasses: [],
            items: [],
            info: "I wanted a fun and challenging way to show off my skills and let people interact with them in real-time.  For me, if I log in to my website I can make these save to a database.  I encourage you to try dragging, dropping and turn on/off skills.",
          },
          {
            id: "covid-19-data-viz",
            link: "https://www.albertsigman.com/visualization-project-001/index.html",
            displayName: "Covid-19 Data Visualization",
            customClasses: [],
            items: [],
          },
          {
            id: "static-web-design",
            link: "https://www.brazeestudios.com/",
            displayName: "Static Site Web Design",
            customClasses: [],
            items: [],
            info: "Here is an example of a website I created in React with the synergy of a web designer.  The client wanted repeatable templates but did not want a complex CMS. ** Our solution was to leverage their existing Google GSuite Tools and the entire website is called a build time from metadata on Google Spreadsheets. ** Images are hosted via a public Google Drive folder and the site is made in Gatsby.js with some clever and complex Node.js config files to build the site the right way.",
          },
        ],
      },
      {
        id: "menu-item--sounds",
        link: "",
        displayName: "Sounds",
        customClasses: ["hover-creative"],
        items: [
          {
            id: "commercial-audio",
            link: "https://youtube.com/playlist?list=PLGVZlmzZDMxIRHtbJ4rzRg0b2aLWrl9fV",
            displayName: "Commercial Audio",
            customClasses: [],
            items: [],
            info: "I have worked with some of the most recognizable companies helping create memorable and fitting music and sound design behind their ads.  ** Click the link to take you to me highlight reel.",
          },
          {
            id: "music-production",
            link: "",
            displayName: "Music Production",
            customClasses: [],
            items: [],
            info: "Before I was a developer I made my living as a full-time music producer, touring artist, and musician.  I am working on getting a gallery of these projects together. ** Check back soon!",
          },
          {
            id: "my-personal-music",
            link: "https://open.spotify.com/artist/0PfHJAlpEVJcWdM5ZUzChk",
            displayName: "My Personal Music",
            customClasses: [],
            items: [],
          },
        ],
      },
      {
        id: "menu-item--words",
        link: "",
        displayName: "Words",
        customClasses: ["hover-other"],
        items: [
          {
            id: "blog",
            link: "",
            displayName: "My Blog",
            customClasses: [],
            items: [],
            info: "Coming Soon!",
          },
          {
            id: "value-statement",
            link: "",
            displayName: "Value Statement",
            customClasses: [],
            items: [],
            info: `In my career I have kept three things to heart.  Be creative, stay curious and always challenge yourself.  In my life so far I have had some amazing opportunities to apply creativity to an ever-changing landscape of projects. 
            ** My journey so far has seen my music on national TV, over 400 shows touring across the country and living and working in some of the most exciting cities around the world.  All the while, I haven’t lost sight of the big picture and what I am passionate about: using my skills to better understand society and hopefully help make it a better place. 
            ** I came to technology in a roundabout way but a way but everyday it seems more like it made sense all along.  Every job I’ve had, I have been magnetically drawn to the technology behind the scenes. 
            ** The age of the internet has brought with it more modern more complex problems.  Complex problems require informed and thoughtful solutions. I look forward to using my ever-growing horizon of skills to help others interact with their environment and understand each other in new and compelling ways.
            `,
          },
        ],
      },
    ],
  },
  {
    id: "menu-item--resume",
    link: "https://drive.google.com/file/d/1UwPI1i2zBmNimsQb5bw-K5aa7lZ0IibD/view?usp=sharing",
    displayName: "Resume",
    customClasses: ["sm", "hover-purp"],
    items: [
      {
        id: "download-pdf",
        link: "https://drive.google.com/file/d/1UwPI1i2zBmNimsQb5bw-K5aa7lZ0IibD/view?usp=sharing",
        displayName: "Download PDF",
        customClasses: [],
        items: [],
      },
      {
        id: "connect-on-linkedin",
        link: "https://www.linkedin.com/in/albertksigman26/",
        displayName: "Connect on LinkedIn",
        customClasses: [],
        items: [],
      },
      {
        id: "projects",
        link: "#projects",
        displayName: "Projects",
        customClasses: [],
        items: [],
        info: "I wanted to create a fun and innovative way to showcase my projects.  This is an ongoing list so check back for updates and new features! ** Have fun clicking around.",
      },
      { id: "", link: "", displayName: "Skills", customClasses: [], items: [] },
    ],
  },
  {
    id: "menu-item--contact",
    link: "",
    displayName: "Connect",
    customClasses: ["sm", "underliney"],
    items: [
      {
        id: "contact",
        link: "",
        displayName: "Email Me",
        customClasses: [],
        items: [],
      },
      {
        id: "connect-on-linkedin",
        link: "https://www.linkedin.com/in/albertksigman26/",
        displayName: "Connect on LinkedIn",
        customClasses: [],
        items: [],
      },
      {
        id: "chat-realtime",
        link: "",
        displayName: "Chat Me Realtime (Coming Soon)",
        customClasses: [],
        items: [],
        info: "Coming Soon! ** I am working on hooking up my Twilio API to this site so you can chat me real-time!",
      },
      {
        id: "contact",
        link: "",
        displayName: "Request a Consultation",
        customClasses: [],
        items: [],
      },
    ],
  },
  {
    id: "everything-else",
    link: "",
    displayName: "Ephemera",
    customClasses: [],
    items: [
      {
        id: "bands",
        link: "",
        displayName: "Bands",
        customClasses: [],
        items: [
          {
            id: "spotify",
            link: "https://open.spotify.com/artist/0PfHJAlpEVJcWdM5ZUzChk",
            displayName: "Spotify",
            customClasses: [],
            items: [],
          },
          {
            id: "soundcloud",
            link: "https://soundcloud.com/enderrr_beatsss",
            displayName: "Soundcloud",
            customClasses: [],
            items: [],
          },
          {
            id: "fluffer",
            link: "https://fluffer.bandcamp.com/",
            displayName: "Fluffer",
            customClasses: [],
            items: [],
          },
          {
            id: "Enderrr",
            link: "https://open.spotify.com/artist/0PfHJAlpEVJcWdM5ZUzChk",
            displayName: "enderrr",
            customClasses: [],
            items: [],
          },
          {
            id: "mungbean",
            link: "https://www.mungbeanmusic.com/",
            displayName: "Mungbean",
            customClasses: [],
            items: [],
          },
        ],
      },
      {
        id: "builds",
        link: "",
        displayName: "Builds",
        customClasses: [],
        items: [
          {
            id: "blink",
            link: "https://www.aggregatedesign.co/work/thecolosseum",
            displayName: "'The Colliseum' Art Installation",
            customClasses: [],
            items: [],
            info: "Using my tech skills and audio production background, I helped some design/fabricator collaborators to create an interactive and immersive live event experience. ** I used DMX driven lights, some custom Python code and alot of elbow grease to create one of the most memorable installations at the bi-annual Cincinnati BLINK! festival.",
          },
          {
            id: "dream-machine",
            link: "https://vimeo.com/229144600",
            displayName: "'The Dream Machine' Art Installation",
            customClasses: [],
            items: [],
            info: `Doing installation work is one of my favorite things as an audio producer. Maybe it is from playing in bands my whole life. Either way, I helped collaborate with HP Innovation to create this gigantic masterpiece, debuted at New York City's "Panorama Music Festival."
            ** We used Max for Live and Ableton all hidden away in the installation to drive the music and instrumentation. What started out with alot of frustrated hours of coding, ended with something truly magical. Watching people's faces when they interacted with the machine was very gratifying. 
            ** I hope that I can continue work like this in the future.`,
          },
          {
            id: "art-prize",
            link: "",
            displayName: "Art Prize | Telephone Booth Installation",
            customClasses: [],
            items: [],
            info: "Coming Soon!",
          },
        ],
      },
      {
        id: "blog",
        link: "",
        displayName: "Blog",
        customClasses: [],
        items: [
          {
            id: "medium",
            link: "",
            displayName: "My Medium",
            customClasses: [],
            items: [],
            info: "Coming Soon!",
          },
          {
            id: "value-statement",
            link: "",
            displayName: "My Value Statement",
            customClasses: [],
            items: [],
            info: `In my career I have kept three things to heart.  Be creative, stay curious and always challenge yourself.  In my life so far I have had some amazing opportunities to apply creativity to an ever-changing landscape of projects. 
            ** My journey so far has seen my music on national TV, over 400 shows touring across the country and living and working in some of the most exciting cities around the world.  All the while, I haven’t lost sight of the big picture and what I am passionate about: using my skills to better understand society and hopefully help make it a better place. 
            ** I came to technology in a roundabout way but a way but everyday it seems more like it made sense all along.  Every job I’ve had, I have been magnetically drawn to the technology behind the scenes. 
            ** The age of the internet has brought with it more modern more complex problems.  Complex problems require informed and thoughtful solutions. I look forward to using my ever-growing horizon of skills to help others interact with their environment and understand each other in new and compelling ways.
            `,
          },
          {
            id: "podcasts",
            link: "",
            displayName: "Podcasts",
            customClasses: [],
            items: [],
            info: "Coming Soon!",
          },
        ],
      },
      {
        id: "books",
        link: "",
        displayName: "Books",
        customClasses: [],
        items: [],
        info: "I am working towards making a list of books, essays and articles that have affected me and made an impact on my values and outlook.  ** Check back soon!",
      },
    ],
  },
];

export default menu_items;
